### PR TITLE
Adding naming convention.

### PR DESCRIPTION
**Pull request by poeschlr**
If you are happy to add it as it is now we can include it in the KLC v3.0 release.

I can make small changes if you require them. But i should focus on university for the next few weeks.

Adding further types of footprints can be done in a KLC v3.0.1 release.
(Still missing: Inductors Transformers, Potentiometers, Resistor arrays, Switches and many more.)

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Rene,

Awesome I'll have a look at this at the end of the weekend, I'm away until Sunday. 

Thanks

**Comment by SchrodingersGat** [comment]
Rene I have made some further changes that have broken this. can you please fix the conflicts? Thanks

**Comment by poeschlr** [comment]
I assume you switched to hugo v0.30 (via snap install)
(The KLC rules are not links with the native 0.16 hugo. Or did i destroy something in the merge process?)

With the snap install i could not get asciidoctor to run. Does this work for you?

**Comment by SchrodingersGat** [comment]
I installed via the .deb package on the hugo github page, and it all worked out of the box for me...

**Pull request merged**
